name: two-photon
channels:
  - conda-forge
  - defaults
dependencies:
  - dask=2.21
  - h5py=2.10.0
  - numpy=1.19.1
  - pandas=1.0.5
  - pip=20.1.1
  - pytables=3.6.1
  - python=3.8.5
  - scikit-image=0.17.2
  - scipy=1.5.2
  - tifffile=2021.4.8
  - yapf
  - pip:
      - suite2p==0.7.5
